api/urls.py
from django.urls import path, include
from .views import SkillsListApiView, CityListApiView



app_name = 'api'

urlpatterns = [
    path('skills/', SkillsListApiView.as_view(), name='skills'),
    path('cities/', CityListApiView.as_view(), name='cities'),
]

teams/urls.py
from django.urls import path
from .views import TeamListView, TeamJoinRequestNotifier, TeamCreate, TeamUpdateView, AddDeleteCandidate

urlpatterns = [
    path('list/', TeamListView.as_view(), name='team-list'),
    # path('join-request/', TeamJoinRequestNotifier.as_view(), name='profile'),
    path('create/', TeamCreate.as_view(), name='team-create'),
    path('update/<int:pk>', TeamUpdateView.as_view(), name='team-update'),
    path('join-request/', AddDeleteCandidate.as_view(), name='join-request'),
]

teams/models.py
from django.db import models
from people.models import Participant, Skill
from hackathon.models import Hackathon
# Create your models here.


class Team(models.Model):
    name        = models.CharField(max_length=100)
    members     = models.ManyToManyField(Participant, related_name='teams')
    teamleader  = models.ForeignKey(Participant, on_delete=models.SET_NULL, null=True, blank=True, related_name='my_teams')
    looking_for = models.BooleanField()
    hackathon   = models.ForeignKey(Hackathon, on_delete=models.CASCADE)
    candidates  = models.ManyToManyField(Participant, blank=True)
    needed_skill = models.ManyToManyField(Skill,blank=True)
    description = models.TextField()

    def __str__(self):
        return self.name

teams/forms.py
from .models import Team
from django import forms
from .models import Team, Participant, Skill


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'needed_skill', 'looking_for', 'description', 'hackathon']


class TeamUpdateForm(forms.ModelForm):
    description = forms.Textarea()
    looking_for = forms.BooleanField(required=False)
    needed_skill = forms.ModelMultipleChoiceField(Skill.objects.all())

    class Meta:
        model = Team
        fields = ['looking_for', 'description', 'needed_skill']

teams/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic.list import ListView
from django.http import JsonResponse
from .models import Team
from .forms import TeamForm, TeamUpdateForm
from people.models import Participant
from django.core.mail import send_mail
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.views import View
from hackworld.settings.base import EMAIL_HOST_USER
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.http import HttpResponseForbidden, JsonResponse
import json
from django.db.models import Q



class AddDeleteCandidate(View):
    def post(self, request):
        data = request.POST
        team = Team.objects.get(id=data['team-id'])
        participant = Participant.objects.get(id=data['user-id'])
        if data['accept']:
            if team.members.count() >= team.hackathon.max_size:
                return {"success": False, 'message':'Maximum team size reached'}
            else:
                team.members.add(participant)
                team.candidates.remove(participant)
                return {"success": True, 'message': f'{participant.name} {participant.surname} added to team!'}
        else:
            team.candidates.remove(participant)
            return {"success": True, 'message': f'{participant.name} {participant.surname} removed from candidates!'}

class JoinRequest(View):
    def post(self, request):
        data = request.POST


class TeamListView(ListView):
    model = Team
    template_name = 'teams/team-list.html'


class TeamJoinRequestNotifier(View):
    def post(self, request):
        team_id = self.request.POST.get('team-id', self.request.GET.get('team-id'))
        try:
            team_id = int(team_id)
        except Exception:
            return JsonResponse({'success': False,
                                 'message': f'Invalid format POST={self.request.POST} GET={request.GET} method={request.method}'})
        participant = Participant.objects.get(user=request.user)
        team = Team.objects.filter(id=team_id)
        if team.count() == 0:
            return JsonResponse({'success': False, 'message': f'No team with id={team_id}'})
        team = team.first()
        if team.members.count() >= team.hackathon.max_size:
            return JsonResponse({'success': False, 'message': f'Team is already full'})
        if team.members.filter(user=participant.user):
            return JsonResponse({'success': False, 'message': f'You are already in this team'})
        if team.candidates.filter(user=participant.user):
            return JsonResponse({'success': False, 'message': f'Your request is already pending'})
        team.candidates.add(participant)
        res = send_mail(
            'Team join request',
            f'User {participant} wants to join your team {team.name}.',
            EMAIL_HOST_USER,
            [team.teamleader.user.email]
        )
        if res:
            return JsonResponse({'success': True, 'message': 'Mail sent'})
        return JsonResponse({'success': False,
                             'message': f'Added to candidates but could not send mail to {team.teamleader.user.email}'})


class TeamCreate(LoginRequiredMixin, CreateView):
    model = Team
    template_name = 'teams/team-create.html'
    form_class = TeamForm

    def form_valid(self, form):
        print('valid')
        instance = form.save(commit=False)
        instance.teamleader = self.request.user.participant
        # participant = self.request.user.participant
        # data = self.request.POST.cleaned_data
        # team = Team(name=data.get('name'), teamleader=participant, looking_for=data.get('looking_for'),
        #             needed_skill=data.get('needed_skill'), description=data.get('description'))
        # team.save()
        instance.hackathon_id = self.request.GET.get('hackathon', 7)
        instance.save()
        instance.members.add(self.request.user.participant)
        instance.save()
        return redirect(reverse('people:profile'))
    def form_invalid(self, form):
        print(form.errors)


class TeamUpdateView(FormView):
    form_class = TeamUpdateForm
    template_name = 'peoples/edit-team.html'
    queryset = Participant.objects.all()
    success_url = '/profile/teams/'
    model = Team

    def dispatch(self, request, *args, **kwargs):
        id = kwargs['pk']
        team = get_object_or_404(Team, pk=id)
        if team.teamleader != request.user.participant:
            return HttpResponseForbidden()
        return super(TeamUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(TeamUpdateView, self).get_context_data(**kwargs)
        context['form'] = self.get_form(self.form_class)
        id = self.kwargs['pk']
        context['members'] = Team.objects.get(pk=id)
        return context

    # def get_form(self, form_class=None):
    #     id = self.kwargs['pk']
    #     team = Team.objects.get(pk=id)
    #     form = self.form_class(
    #         initial={'description': team.description,
    #                  'looking_for': team.looking_for,
    #                  'needed_skill': team.needed_skill.all()
    #                  })
    #     return form

templates/teams/team-create.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/registration.css'%}">
{% endblock %}

{% block content %}
    {% comment %} {{ form.as_p }} {% endcomment %}
    <header class="header-main">
        Create team
    </header>
    <form class="register-form" method="post">
        {% comment %} {{ form.errors }} {% endcomment %}
        <fieldset>
            <input type="hidden" name="hackathon" value="{{ request.GET.hackathon }}">
        </fieldset>
        <fieldset>
            <label for="name">Team name</label>
            <div class="errortext">{{ form.name.errors }}</div>
            {{ form.name|attr:'class=regular-input'|attr:'id=name' }}
        </fieldset>
        <fieldset>
            <label for="needed_skill">Needed skills</label>
            <div class="errortext">{{ form.needed_skill.errors }}</div>
            <input type='text' class='search-input' autocomplete='off' placeholder='Start typing...'>
            <select id="skills" class="multiselect" multiple="multiple"></select>
            <select name="needed_skill" id="skills_to" class="multiselect" multiple="multiple"></select>
            {% comment %} {{ form.needed_skill|attr:'class=regular-input'|attr:'id=needed_skill' }} {% endcomment %}
        </fieldset>
        <fieldset class="checkbox">
            <label for="looking_for">Looking for new members? {{ form.looking_for|attr:'class=regular-input'|attr:'id=looking_for' }}</label>
            <div class="errortext">{{ form.looking_for.errors }}</div>
        </fieldset>
        <fieldset>
            <label for="description">Description</label>
            <div class="errortext">{{ form.description.errors }}</div>
            {{ form.description|attr:'class=regular-input'|attr:'id=description' }}
        </fieldset>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/multiselect.min.js' %}"></script>
    <script src="{% static 'js/skill-select.js' %}"></script>
    <script>initMultiselect();</script>
{% endblock %}

templates/teams/team-list.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Your teams{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/hackaton-details.css' %}">
{% endblock %}

{% block content %}
    <header class="header-main">
        Your teams
    </header>
    <div class="hackaton-details">
        <div class="hackaton-teams">
            <div class="hackaton-teams-featured">
                <div class="hackaton-teams-header">
                    Teams you are leader in
                </div>
                <div class="hackaton-teams-list">
                    {% for team in team_list %}
                        <div class="hackaton-team">
                            <div class="data">
                                <div class="name">{{team.name}}</div>
                                <div class="members">
                                    <div class="member leader">{{ team.teamleader }}</div>
                                    {% for member in team.members.all %}
                                        {% if member != team.teamleader %}
                                            <div class="member">{{ member }}</div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                                <div class="join-requests">
                                    <img src="{% static 'img/icons8-high-priority-48.png' %}">
                                    3 join requests!
                                </div>
                            </div>
                        </div>

                            {% comment %} {% if team.looking_for %}
                                <p> Looking for team leader </p>
                            {% endif %} {% endcomment %}
                    {% endfor %}
                </div>
                    {% comment %} <div class="hackaton-team">
                        <div>
                            <div class="data">
                                <div class="name">theBrokenLemurs</div>
                                <div class="members">
                                    <div class="member leader">Kamil Krzempek</div>
                                    <div class="member">Szymon Cader</div>
                                    <div class="member">Grzegorz Nieużyła</div>
                                </div>
                                <div class="join-requests">
                                    <img src="../img/icons8-high-priority-48.png">
                                    3 join requests!
                                </div>
                            </div>
                            <div class="needed">
                                You are looking for
                                <div class="skill-list">
                                    <div class="skill">Scrum master</div>
                                    <div class="skill">Javascript</div>
                                    <div class="skill">Wordpress developer</div>
                                </div>
                                <button>Edit team</button>
                            </div>
                        </div>
                        <div class="requests expand">
                            <div class="request">
                                <div class="user">Paweł Tomana</div>
                                <div class="accept"><img src="../img/icons8-ok-48.png"></div>
                                <div class="decline"><img src="../img/icons8-cancel-48.png"></div>
                            </div>
                            <div class="request">
                                <div class="user">Paweł Tomana</div>
                                <div class="accept"><img src="../img/icons8-ok-48.png"></div>
                                <div class="decline"><img src="../img/icons8-cancel-48.png"></div>
                            </div>
                            <div class="request">
                                <div class="user">Paweł Tomana</div>
                                <div class="accept"><img src="../img/icons8-ok-48.png"></div>
                                <div class="decline"><img src="../img/icons8-cancel-48.png"></div>
                            </div>
                        </div>
                    </div> {% endcomment %}
            </div>
            <div class="hackaton-teams-other">
                <div class="hackaton-teams-header">
                    Teams you are member of
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}