api/urls.py
from django.urls import path, include
from .views import SkillsListApiView, CityListApiView



app_name = 'api'

urlpatterns = [
    path('skills/', SkillsListApiView.as_view(), name='skills'),
    path('cities/', CityListApiView.as_view(), name='cities'),
]

people/urls.py
from django.urls import path
from .views import ParticipantCreate, LoginView, LogoutView, ProfileView, ParticipantCreateView, ParticipantUpdateView,\
                    Participantformset, DescriptionUpdateView, AlienProfileView, TeamListView

app_name = 'people'
urlpatterns = [
    path('register/', ParticipantCreate.as_view(), name='user-register'),
    path('skills/', Participantformset.as_view(), name='skills-edit'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('teams/', TeamListView.as_view(), name='teams-list'),
    path('', ProfileView.as_view(), name='profile'),
    path('update/', ParticipantUpdateView.as_view(), name='update'),
    path('description/', DescriptionUpdateView.as_view(), name='description'),
    path('<int:pk>/', AlienProfileView.as_view(), name='alien-profile'),
]

people/models.py
from django.db import models
from django.core.validators import ValidationError
from django.contrib.auth.models import User
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.shortcuts import reverse
# Create your models here.

def advance_level_validator(value):
    if value < 1 or value > 10:
        raise ValidationError("Provide number between 1 and 10")

def get_user():
    return User.objects.first().id

class City(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "City"
        verbose_name_plural = "Cities"


class Skill(models.Model):
    name            = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class ParticipantSkill(models.Model):
    skill            = models.ForeignKey(Skill, on_delete=models.CASCADE)
    advanced_level  = models. SmallIntegerField(validators=[advance_level_validator,], default=1)
    participant     = models.ForeignKey('Participant', on_delete=models.CASCADE)

    def __str__(self):
        return  self.skill.name

class Participant(models.Model):
    user                = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    name                = models.CharField(max_length=50)
    surname             = models.CharField(max_length=50)
    city                = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True)
    short_description   = models.CharField(max_length=100, blank=True)
    description         = models.TextField(blank=True)
    linkedin_url        = models.URLField(blank=True)
    github_url          = models.URLField(blank=True)
    # email       = models.EmailField()
    # skills      = models.ManyToManyField(ParticipantSkill, blank=True, related_name='participants')

    def __str__(self):
        return f"{self.name} {self.surname}"

    def get_absolute_url(self):
        return reverse('people:alien-profile', args=(self.id,))




@receiver(post_delete, sender=Participant)
def auto_delete_user(sender, instance, **kwargs):
    if instance.user:
        instance.user.delete()

templates/peoples/alien_profile.html
{% extends "base.html" %}

{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Profil{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}

{% block content %}
    <header class="header-main">
        <div>
            <div class="header-text">{{ participant.name }} {{ participant.surname }}</div>
            <div class="header-subtext">{{ participant.short_description }}</div>
        </div>
        <div class="header-image"><img src="{% static '/img/avatar.jpg' %}"></div>
    </header>
    <div class="user-details" data-id="{{ participant.id }}">
        <div class="user-description">
            <div class="header">Description</div>
            <div class="description">
                {{ participant.description }}<br>

            </div>
        </div>
        <div class="user-skills">
            <div class="header">Skills</div>
            <div class="user-skills-list block">
                {% for skill in participant.participantskill_set.all %}
                    <div class="user-skill">
                        <div class="name">{{ skill.skill.name }}</div>
                        <div class="c-rating c-rating--big" data-rating-value="{{ skill.advanced_level }}">
                            <button>1</button>
                            <button>2</button>
                            <button>3</button>
                            <button>4</button>
                            <button>5</button>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="button" id="skills-send">Save</div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

templates/peoples/edit-profile.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Log in!{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}

{% block content %}
    <header class="header-main">
        Edit personal data
    </header>
    {{ form.errors }}
    <form class="register-form" method="post">
        <fieldset>
{#            <label for="email">Email</label>#}
{#            <input class="regular-input" type="text" id="email" name="email">#}
            <label for="email">Email</label>
            <div class="errortext">{{ form.email.errors }}</div>
            {{ form.email|attr:'class=regular-input'|attr:'id=email' }}
        </fieldset>
        <!--<fieldset>-->
<!--{#            <label for="password">Password</label>#}-->
<!--{#            <input class="regular-input" type="password" id="password" name="password">#}-->
            <!--<label for="password">Password</label>-->
                <!--<div class="errortext">{{ form.password1.errors }}</div>-->
<!--{#                <input class="regular-input" type="password" id="password" name="password">#}-->
                <!--{{ form.password1|attr:'class=regular-input'|attr:'id=passsword' }}-->
        <!--</fieldset>-->
        <!--<fieldset>-->
<!--{#            <label for="repeat-password">Repeat password</label>#}-->
<!--{#            <input class="regular-input" type="password" id="repeat-password" name="repeat-password">#}-->
            <!--<label for="repeat-password">Repeat password</label>-->
                <!--<div class="errortext">{{ form.password2.errors }}</div>-->
<!--{#                <input class="regular-input" type="password" id="repeat-password" name="repeat-password">#}-->
                <!--{{ form.password2|attr:'class=regular-input'|attr:'id=repeat-password' }}-->
        <!--</fieldset>-->
        <fieldset>
            <label for="name">First name</label>
{#            <input class="regular-input" type="text" id="name" name="name">#}
                <div class="errortext">{{ form.name.errors }}</div>
{#                <input class="regular-input" type="text" id="surname" name="surname">#}
                    {{ form.name|attr:'class=regular-input'|attr:'id=surname' }}
        </fieldset>
        <fieldset>
{#            <label for="surname">Last name</label>#}
{#            <input class="regular-input" type="text" id="surname" name="surname">#}
                <label for="surname">Last name</label>
                <div class="errortext">{{ form.surname.errors }}</div>
{#                <input class="regular-input" type="text" id="surname" name="surname">#}
                    {{ form.surname|attr:'class=regular-input'|attr:'id=surname' }}
        </fieldset>
        <fieldset>
            <label for="short-description">Short description</label>
{#            <input class="regular-input" type="text" id="short-description" name="short-description">#}
            {{ form.short_description|attr:'class=regular-input'|attr:'id=surname' }}
        </fieldset>
        <fieldset>
            {% comment %} <label for="city">City</label>
            <input class="regular-input" list="cities" type="text" id="city" name="city">
            <datalist id="cities"></datalist> {% endcomment %}
            <label for="location">Where are you from?</label>
{#                <input class="regular-input" list="cities" type="text" id="city" name="city">#}
                <div class="errortext">{{ form.city.errors }}</div>
                {{ form.city|attr:'class=regular-input'|attr:'id=location'|attr:'list=cities' }}
                <datalist id="cities"></datalist>
        </fieldset>
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/location-select.js' %}"></script>
{% endblock scripts %}

templates/peoples/edit-team.html
{% extends "base.html" %}
{% block content %}

{{ form.as_p }}

{% endblock %}

templates/peoples/login.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Log in!{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}

{% block content %}
    <header class="header-main">
        Log in to your account!
    </header>
    <form method="POST" class="register-form" action="{% url 'people:login' %}">
        {% csrf_token %}
{#            {{ form.as_p }}#}
        <div class="errortext">
            {{ form.errors }}
        </div>
        <fieldset>
            <label for="login">Login</label>
            <div class="errortext">{{ form.username.errors }}</div>
{#                <input class="regular-input" type="text" id="login" name="login">#}
            {{ form.username|attr:'class=regular-input'|attr:'id=login' }}
        </fieldset>
        <fieldset>
            <label for="password">Password</label>
            <div class="errortext">{{ form.password.errors }}</div>
            {% comment %} <input class="regular-input" type="password" id="password" name="password"> {% endcomment %}
            {{ form.password|attr:'class=regular-input'|attr:'id=passsword' }}
        </fieldset>
        <div class="buttons">
            <input type="submit" value="Submit">
        </div>
    </form>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

templates/peoples/profile.html
{% extends "base.html" %}

{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Profil{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}

{% block content %}
    <header class="header-main">
        <div>
            <div class="header-text">{{ participant.name }} {{ participant.surname }}</div>
            <div class="header-subtext">{{ participant.short_description }}</div>
        </div>
        <div class="header-image"><img src="{% static '/img/avatar.jpg' %}"></div>
    </header>
    <div class="user-details" data-id="{{ participant.id }}">
        <div class="user-edit">
            <a href="{% url 'people:update' %}"><div class="button">Edit personal data</div></a>
            <!-- <a href="{% url 'people:update' %}"><div class="button">Change password</div></a> -->
        </div>
        <div class="user-description">
            <div class="header">Description <span id="description-edit"><img src="{% static 'img/icons8-edit-filled-50.png' %}"></span></div>
            <div class="description">
                    {{ participant.description }}
            </div>
            {% comment %} SET FORM ACTION {% endcomment %}
            <form method="POST" action="{% url 'people:description' %}">
                <textarea name="description" id="description"></textarea>
                    {{ form.description|attr:"id=description" }}
                <input type="submit" class="button" value="Save">
            </form>
        </div>
        <div class="user-skills">
            <div class="header">Skills <span id="skills-edit"><img src="{% static 'img/icons8-edit-filled-50.png' %}"></span></div>
            <div class="user-skills-list block">
                {% for skill in participant.participantskill_set.all %}
                    <div class="user-skill" data-id="{{ skill.id }}">
                        <div class="name" data-id="{{ skill.skill.id }}">{{ skill.skill.name }}</div>
                        <div class="c-rating c-rating--big" data-rating-value="{{ skill.advanced_level }}">
                            <button>1</button>
                            <button>2</button>
                            <button>3</button>
                            <button>4</button>
                            <button>5</button>
                        </div>
                        <div class="remove"><img src="{% static 'img/icons8-cancel-48.png' %}"></div>
                    </div>
                {% endfor %}
                <div class="add"><img src="{% static 'img/icons8-plus-48.png' %}"></div>
{##}
{#                <div class="user-skill">#}
{#                    <div class="name">Wordpress development</div>#}
{#                    <div class="c-rating c-rating--big" data-rating-value="3">#}
{#                        <button>1</button>#}
{#                        <button>2</button>#}
{#                        <button>3</button>#}
{#                        <button>4</button>#}
{#                        <button>5</button>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="user-skill">#}
{#                    <div class="name">Javascript</div>#}
{#                    <div class="c-rating c-rating--big" data-rating-value="2">#}
{#                        <button>1</button>#}
{#                        <button>2</button>#}
{#                        <button>3</button>#}
{#                        <button>4</button>#}
{#                        <button>5</button>#}
{#                    </div>#}
{#                </div>#}
            </div>
            <div class="button" id="skills-send">Save</div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/skill-select.js' %}"></script>
    <script src="{% static 'js/profile-edit.js' %}"></script>
{% endblock scripts %}

{% comment %} {% block content %}
{% for team in teams.all %}

{{participant.surname}}

<p>Team: {{ team }}</p>
    {% for member in team.members.all %}
        {% if member != participant %}
        <p>Member: {{ member }}</p>
        {% endif %}

    {% endfor %}

{% endfor %}
{% endblock %} {% endcomment %}

templates/peoples/registration.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Join us!{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}

{% block content %}
    <header class="header-main">
        Join us!
    </header>
{#    {{ form.errors }}#}
    <form method="POST" class="register-form multiform" action="{% url 'people:user-register' %}">
        {% csrf_token %}
        <div class="step">
            <!-- <div class="step-number"><span>1</span></div> -->
{#            {{ form.as_p }}#}
            <fieldset>
                <label for="login">Login</label>
                <div class="errortext">{{ form.username.errors }}</div>
{#                <input class="regular-input" type="text" id="login" name="login">#}
                {{ form.username|attr:'class=regular-input'|attr:'id=login' }}
            </fieldset>
            <fieldset>
                <label for="email">Email</label>
                <div class="errortext">{{ form.email.errors }}</div>
{#                <input class="regular-input" type="text" id="email" name="email">#}
                {{ form.email|attr:'class=regular-input'|attr:'id=email' }}
            </fieldset>
            <fieldset>
                <label for="password">Password</label>
                <div class="errortext">{{ form.password1.errors }}</div>
{#                <input class="regular-input" type="password" id="password" name="password">#}
                {{ form.password1|attr:'class=regular-input'|attr:'id=passsword' }}
            </fieldset>
            <fieldset>
                <label for="repeat-password">Repeat password</label>
                <div class="errortext">{{ form.password2.errors }}</div>
{#                <input class="regular-input" type="password" id="repeat-password" name="repeat-password">#}
                {{ form.password2|attr:'class=regular-input'|attr:'id=repeat-password' }}
            </fieldset>
            <div class="buttons">
                <button class="next-step">Next &gt;</button>
            </div>
        </div>
        <div class="step">
            <fieldset>
                <label for="name">First name</label>
                <div class="errortext">{{ form.name.errors }}</div>
{#                <input class="regular-input" type="text" id="name" name="name">#}
                {{ form.name|attr:'class=regular-input'|attr:'id=name'}}
            </fieldset>
            <fieldset>
                <label for="surname">Last name</label>
                <div class="errortext">{{ form.surname.errors }}</div>
{#                <input class="regular-input" type="text" id="surname" name="surname">#}
                    {{ form.surname|attr:'class=regular-input'|attr:'id=surname' }}
            </fieldset>
            <fieldset>
                <label for="location">Where are you from?</label>
{#                <input class="regular-input" list="cities" type="text" id="city" name="city">#}
                <div class="errortext">{{ form.city.errors }}</div>
                {{ form.city|attr:'class=regular-input'|attr:'id=location'|attr:'list=cities' }}
                <datalist id="cities"></datalist>
            </fieldset>
            <div class="buttons">
                <button class="prev-step">&lt; Back</button>
                <button class="next-step">Next &gt;</button>
            </div>
        </div>
        <div class="step">
            <fieldset>
                <label for="programming-skills">Programming skills</label>
                <div class="errortext">{{ form.skill.errors }}</div>
                <input type='text' class='search-input' autocomplete='off' placeholder='Start typing...'>
                <select id="skills" class="multiselect" multiple="multiple">
                </select>
                <select name="skills" id="skills_to" class="multiselect" multiple="multiple"></select>
            </fieldset>
            <div class="buttons">
                <button class="prev-step">&lt;Back</button>
                <input type="submit" value="Submit">
            </div>
        </div>
    </form>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/multiselect.min.js' %}"></script>
    <script src="{% static 'js/location-select.js' %}"></script>
    <script src="{% static 'js/skill-select.js' %}"></script>
    <script>initMultiselect();</script>
    <script src="{% static 'js/register-form.js' %}"></script>
{% endblock scripts %}

templates/peoples/team_list.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Your teams{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/hackaton-details.css' %}">
{% endblock %}

{% block content %}
    <header class="header-main">
        Your teams
    </header>
    <div class="hackaton-details">
        <div class="hackaton-teams">
            <div class="hackaton-teams-featured">
                <div class="hackaton-teams-header">
                    Teams you are leader in
                </div>
                <div class="hackaton-teams-list">
                    {% for team in team_list %}
                        {% if team.teamleader == request.user.participant %}
                            <div class="hackaton-team">
                                <div>
                                    <div class="data">
                                        <div class="name">{{team.name}}</div>
                                        <div class="members">
                                            <div class="member leader">{{ team.teamleader }}</div>
                                            {% for member in team.members.all %}
                                                {% if member != team.teamleader %}
                                                    <div class="member">{{ member }}</div>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                        {% comment %} <div class="join-requests">
                                            <img src="{% static 'img/icons8-high-priority-48.png' %}">
                                            3 join requests!
                                        </div> {% endcomment %}
                                    </div>
                                    <div class="needed">
                                        You are looking for
                                        <div class="skill-list">
                                            {% for skill in team.needed_skill.all %}
                                                <div class="skill">{{skill.name}}</div>
                                            {% endfor %}
                                        </div>
                                        <button>Edit team</button>
                                    </div>
                                </div>
                                <div class="requests expand">
                                    {% for request in team.candidates.all %}
                                        <div class="request" data-userid="{{ request.user.participant.id }}" data-teamid="{{ team.id }}">
                                            <div class="user">{{ request.user.participant }}</div>
                                            <div class="accept"><img src="{% static 'img/icons8-ok-48.png' %}"></div>
                                            <div class="decline"><img src="{% static 'img/icons8-cancel-48.png' %}"></div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        {% endif %}
                            {% comment %} {% if team.looking_for %}
                                <p> Looking for team leader </p>
                            {% endif %} {% endcomment %}
                    {% endfor %}
                </div>
            </div>
            <div class="hackaton-teams-other">
                <div class="hackaton-teams-header">
                    Teams you are member of
                </div>
                <div class="hackaton-teams-list">
                    {% for team in team_list %}
                        {% if team.teamleader != request.user.participant %}
                            <div class="hackaton-team">
                                <div class="data">
                                    <div class="name">{{team.name}}</div>
                                    <div class="members">
                                        <div class="member leader">{{ team.teamleader }}</div>
                                        {% for member in team.members.all %}
                                            {% if member != team.teamleader %}
                                                <div class="member">{{ member }}</div>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                    {% comment %} <div class="join-requests">
                                        <img src="{% static 'img/icons8-high-priority-48.png' %}">
                                        3 join requests!
                                    </div> {% endcomment %}
                                </div>
                                <div class="needed">
                                    You are looking for
                                    <div class="skill-list">
                                        {% for skill in team.needed_skill.all %}
                                            <div class="skill">{{skill.name}}</div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                            {% comment %} {% if team.looking_for %}
                                <p> Looking for team leader </p>
                            {% endif %} {% endcomment %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/join-request.js' %}"></script>
{% endblock scripts %}