api/urls.py
from django.urls import path, include
from .views import SkillsListApiView, CityListApiView



app_name = 'api'

urlpatterns = [
    path('skills/', SkillsListApiView.as_view(), name='skills'),
    path('cities/', CityListApiView.as_view(), name='cities'),
]

hackathon/urls.py
from django.urls import path
from .views import HackathonCreateView, HackathonDetailView

app_name = 'hackathon'

urlpatterns = [
    path('create', HackathonCreateView.as_view(), name='create'),
    path('<int:id>', HackathonDetailView.as_view(), name='detail'),
]

people/urls.py
from django.urls import path
from .views import ParticipantCreate, LoginView, LogoutView, ProfileView, ParticipantCreateView, ParticipantUpdateView,\
                    Participantformset, DescriptionUpdateView, AlienProfileView, TeamListView

app_name = 'people'
urlpatterns = [
    path('register/', ParticipantCreate.as_view(), name='user-register'),
    path('skills/', Participantformset.as_view(), name='skills-edit'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('teams/', TeamListView.as_view(), name='teams-list'),
    path('', ProfileView.as_view(), name='profile'),
    path('update/', ParticipantUpdateView.as_view(), name='update'),
    path('description/', DescriptionUpdateView.as_view(), name='description'),
    path('<int:pk>/', AlienProfileView.as_view(), name='alien-profile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}{% endblock %}
</head>
<body>
    <div class="container">
        <aside class="menu-wrapper">
            <div class="menu-container">
                <div class="menu-header">
                    <div></div>
                    <a href="/">
                        <div class="menu-logo">
                            HackWorld
                        </div> 
                    </a>
                    <div class="menu-hamburger">
                        <div class="bar1"></div>
                        <div class="bar2"></div>
                        <div class="bar3"></div>
                    </div>
                </div>
                <div class="menu-options">
                    {% if request.user.is_anonymous %}
                        <a href="{% url 'people:login' %}"><div class="menu-option">Login</div></a>
                        <a href="{% url 'people:user-register' %}"><div class="menu-option">Register</div></a>
                    {% else %}
                        <a href="{% url 'people:logout' %}"><div class="menu-option">Logout</div></a>
                        <a href="{% url 'people:profile' %}"><div class="menu-option">Edit profile</div></a>
                        <a href="{% url 'hackathon:create' %}"><div class="menu-option">Submit a hackathon</div></a>
                        <a href="{% url 'people:teams-list' %}"><div class="menu-option">Your teams</div></a>
                    {% endif %}
                </div>
            </div>
        </aside>
        <main>
            {% block content %}{% endblock %}
        </main>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="{% static 'js/menu.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

templates/tesst.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
{{ skill_formset.media }}

    {% for f in skill_formset %}
<div class="individual-form">
{{ f.as_p }}
</div>
    {% endfor %}
{#    elo{{ skill_formset.as_p }}elo#}
    <input type="submit", value="wyslij">
</form>
<script src="{% static "dynamic_formsets/jquery.formset.js" %}" type="text/javascript"> </script>

<script type="text/javascript">
$('.individual-form').formset();
</script>
</body>
</html>