api/urls.py
from django.urls import path, include
from .views import SkillsListApiView, CityListApiView



app_name = 'api'

urlpatterns = [
    path('skills/', SkillsListApiView.as_view(), name='skills'),
    path('cities/', CityListApiView.as_view(), name='cities'),
]

hackathon/urls.py
from django.urls import path
from .views import HackathonCreateView, HackathonDetailView

app_name = 'hackathon'

urlpatterns = [
    path('create', HackathonCreateView.as_view(), name='create'),
    path('<int:id>', HackathonDetailView.as_view(), name='detail'),
]

hackathon/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from people.models import get_user


# Create your models here.


class Hackathon(models.Model):
    name = models.CharField(max_length=100)
    official_website = models.URLField(blank=True)
    place_url = models.URLField(blank=True)
    place = models.CharField(max_length=100, blank=True)
    accepted = models.BooleanField(default=False)
    description = models.TextField()
    proof = models.TextField(help_text='Put here any information about hackathon and optional links to facebook'
                                       'event or official website ')
    added_by = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=get_user)
    max_size = models.PositiveIntegerField(default=4)
    facebook_page = models.URLField(blank=True)
    date = models.DateTimeField(default=datetime.now)
    image = models.ImageField(blank=True, upload_to='')

    def __str__(self):
        return self.name

hackathon/forms.py
from django import forms
from .models import Hackathon


class HackathonForm(forms.ModelForm):
    class Meta:
        model = Hackathon
        fields = (
            'name', 'proof', 'official_website', 'facebook_page', 'date', 'image', 'place_url', 'place',
            'max_size')

hackathon/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from .models import Hackathon
from teams.models import Team
from people.models import Participant
from .forms import HackathonForm
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.db.models import Count, Q
from django.contrib.auth.mixins import LoginRequiredMixin


class HackathonCreateView(LoginRequiredMixin, CreateView):
    model = Hackathon
    form_class = HackathonForm
    template_name = 'hackathon/hackathon-create.html'

    # success_url = '/'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        message = f'Succesfully added hackathon "{instance.name}", now wait for admin confirmation'
        return render(self.request, 'hackathon/hackathon_create_success.html', context={'message': message})


class MainPage(ListView):
    template_name = 'hackathon/main-page.html'
    context_object_name = 'hackathons'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MainPage, self).get_context_data(**kwargs)

        comp = 0
        context['counts'] = {1: 12, 2: 123}
        context['incomplete_count'] = 0
        context['complete_count'] = 0
        context['res'] = self.get_queryset()
        return context

    def get_queryset(self):
        res = list(
            Hackathon.objects.filter(accepted=True).values('id', 'name', 'official_website', 'place_url', 'place',
                                                           'description', 'max_size', 'facebook_page', 'image', 'date'))
        for hack in res:
            hack['complete_c'] = 0
            hack['incomplete_c'] = 0
            for team in Team.objects.filter(hackathon__id=hack['id']):
                if team.members.count() >= hack['max_size']:
                    hack['complete_c'] += 1
                else:
                    hack['incomplete_c'] += 1
        return res


class HackathonDetailView(LoginRequiredMixin, ListView):
    # model = Team
    template_name = 'hackathon/hackathon_team_list.html'

    def get_context_data(self, object_list=None, **kwargs):
        context = super(HackathonDetailView, self).get_context_data(**kwargs)
        context['hackathon'] = Hackathon.objects.get(id=self.kwargs['id'])
        context['queryset']  = self.get_queryset()
        if Team.objects.filter(hackathon__id=self.kwargs['id']).filter(Q(members=self.request.user.participant)| Q(teamleader=self.request.user.participant)).exists():
            context['has_team'] = True
            context['my_skills'] = list(self.request.user.participant.participantskill_set.values_list('skill__id',flat=True))
            print(context['my_skills'])
            context['my_team'] = Team.objects.filter(hackathon__id=self.kwargs['id']).filter(Q(members=self.request.user.participant) | Q(teamleader=self.request.user.participant)).distinct()
            context['queryset'] = self.get_queryset().exclude(name=Team.objects.filter(hackathon__id=self.kwargs['id']).filter(Q(members=self.request.user.participant) | Q(teamleader=self.request.user.participant)).distinct().first().name)
        return context

    def get_queryset(self):
        return Team.objects.filter(hackathon__id=self.kwargs['id'], looking_for=True)

templates/hackathon/hackathon-create.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/registration.css'%}">
{% endblock %}

{% block content %}
{% comment %} {{ form.as_p }} {% endcomment %}
    <header class="header-main">
        Submit hackathon
    </header>
    <form class="register-form" method="post">
        {{ form.errors }}
        <fieldset>
            <label for="name">Hackathon name</label>
            <div class="errortext">{{ form.name.errors }}</div>
            {{ form.name|attr:'class=regular-input'|attr:'id=name' }}
        </fieldset>
        <fieldset>
            <label for="proof">Description</label>
            <div class="errortext">{{ form.proof.errors }}</div>
            {{ form.proof|attr:'class=regular-input'|attr:'id=proof' }}
        </fieldset>
        <fieldset>
            <label for="image">Hackathon logo</label>
            <div class="errortext">{{ form.image.errors }}</div>
            {{ form.image|attr:'class=regular-input'|attr:'id=image' }}
        </fieldset>
        <fieldset>
            <label for="official_website">Official website</label>
            <div class="errortext">{{ form.official_website.errors }}</div>
            {{ form.official_website|attr:'class=regular-input'|attr:'id=official_website' }}
        </fieldset>
        <fieldset>
            <label for="facebook_page">Facebook page</label>
            <div class="errortext">{{ form.facebook_page.errors }}</div>
            {{ form.facebook_page|attr:'class=regular-input'|attr:'id=facebook_page' }}
        </fieldset>
        <fieldset>
            <label for="date">Event date</label>
            <div class="errortext">{{ form.date.errors }}</div>
            {{ form.date|attr:'class=regular-input'|attr:'id=date' }}
        </fieldset>
        <fieldset>
            <label for="place">Place address</label>
            <div class="errortext">{{ form.place.errors }}</div>
            {{ form.place|attr:'class=regular-input'|attr:'id=place' }}
        </fieldset>
        <fieldset>
            <label for="place_url">Place url</label>
            <div class="errortext">{{ form.place_url.errors }}</div>
            {{ form.place_url|attr:'class=regular-input'|attr:'id=place_url' }}
        </fieldset>
        <fieldset>
            <label for="max_size">Max team size</label>
            <div class="errortext">{{ form.max_size.errors }}</div>
            {{ form.max_size|attr:'class=regular-input'|attr:'id=max_size' }}
        </fieldset>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/hackathon/hackathon_create_success.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Success{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/basic.css' %}">
{% endblock %}

{% block content %}
    <header class="header-main">
        Hackathon submitted!
    </header>
    <div class="message">
        {{ message }}
    </div>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

templates/hackathon/hackathon_team_list.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Team list in hackathon{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/hackaton-details.css' %}">
{% endblock %}

{% block content %}
    <header class="header-main">
        <div>
            <div class="header-text">{{ hackathon.name }}</div>
            <div class="header-subtext">{{ hackathon.place }}</div>
        </div>
        <div class="header-image"><img src="{% static 'img/bitehack.png' %}"></div>
    </header>
    <div class="hackaton-details">
        <div class="hackaton-teams">
            {% if not my_team %}
            <a href="{% url 'team-create' %}?hackathon={{ hackathon.id }}">
                <div class="add-team">
                    <img src="{% static 'img/icons8-plus-filled-50.png' %}">
                    Create team
                </div>
            </a>
            {% else %}
            <a href="#">
                <div class="your-team">
                    <img src="{% static 'img/icons8-edit-filled-50.png' %}">
                    {{ my_team.first.name }}
                </div>
            </a>
            {% endif %}

            <div class="hackaton-teams-featured">
                <div class="hackaton-teams-header">
                    Teams searching for people
                </div>
                <div class="hackaton-teams-list">

                    {% for team in queryset %}

                        <div class="hackaton-team">
                        <div class="data">
                            <div class="name">{{ team.name }}</div>
                            <div class="members">
                                <a href="{{ team.teamleader.get_absolute_url }} "><div class="member leader">{{ team.teamleader.name }} {{ team.teamleader.surname }}</div></a>
                                {% for member in team.members.all %}
                                    {% if member != team.teamleader %}
                                        <a href="{{ member.get_absolute_url }}"><div class="member">{{ member.name }} {{ member.surname }}</div></a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="needed">
                            Team looks for
                            <div class="skill-list">
                                {% for skill in team.needed_skill.all %}
                                <div class="skill {% if skill.id not in my_skills%}not-{% endif %}owned">{{ skill.name }}</div>
                                {% endfor %}

{#                                <div class="skill owned">Scrum master</div>#}
{#                                <div class="skill not-owned">Javascript</div>#}
{#                                <div class="skill owned">Wordpress developer</div>#}
                            </div>
                            <button data-id="{{ team.id }}" class="join-request">Send join request</button>
                        </div>
                    </div>
            {% endfor %}

                </div>
            </div>
{#            <div class="hackaton-teams-other">#}
{#                <div class="hackaton-teams-header">#}
{#                    Other teams#}
{#                </div>#}
            </div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/join-request.js' %}"></script>
{% endblock scripts %}

templates/hackathon/main-page.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Log in!{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/feed.css' %}">
{% endblock %}

{% block content %}
<header class="header-main">
    Upcoming hackatons
</header>
<div class="hackatons">
    {% for hackathon in hackathons %}
        <article class="hackaton">
            <div class="hackaton-base">
                <div>
                    <div class="hackaton-name">{{ hackathon.name }}</div>
                    {% if hackathon.place_url %}<a href="{{ hackathon.place_url }}" target="_blank">{% endif %}
                    <div class="hackaton-place">{{ hackathon.place }}</div>
                    {% if hackathon.place_url %}</a>{% endif %}
                </div>
                {% if hackathon.image %}<div class="hackaton-logo   "><img src="{{ hackathon.image.url }}"></div>{% endif %}
            </div>
            <div class="hackaton-description">{{ hackathon.description }}</div>
            <a href="{% url 'hackathon:detail' id=hackathon.id %}">
                <div class="hackaton-teams">
                    {{ hackathon.complete_c }} full team(s), {{hackathon.incomplete_c}} team(s) looking for members
                </div>
            </a>
            <div class="hackaton-links">
            {% if hackathon.official_website %}
            <a href="{{ hackathon.official_website }}" target="_blank">
                <div class="hackaton-link"><img src="{% static 'img/icons8-internet-50.png' %}"><span>Hackaton website</span></div>
            </a>
            {% endif %}

            {% if hackathon.facebook_page %}
            <a href="{{ hackathon.facebook_page }}" target="_blank">
                <div class="hackaton-link"><img src="{% static 'img/icons8-facebook-50.png' %}"><span>Facebok page</span></div>
            </a>
            {% endif %}
            </div>
        </article>

    {% endfor %}
</div>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}